/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-06-30 08:05:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class myInfoPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	Member member = (Member)request.getAttribute("member");

	//취미 : 하나의 문자열을 "," 로 각각 분리 처리
	String[] hobbies = member.getHobby().split(",");
	
	//checkbox 의 checked 속성 설정을 위한 배열 만듦
	String[] checked = new String[9];
	
	for(String hobby : hobbies){
		switch(hobby){
		case "game": checked[0] = "checked";  break;
		case "reading": checked[1] = "checked";  break;
		case "climb": checked[2] = "checked";  break;
		case "sport": checked[3] = "checked";  break;
		case "music": checked[4] = "checked";  break;
		case "movie": checked[5] = "checked";  break;
		case "travel": checked[6] = "checked";  break;
		case "cook": checked[7] = "checked";  break;
		case "etc": checked[8] = "checked";  break;
		}
	}

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>first</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	table th { background-color: #99ffff; }\r\n");
      out.write("	table#outer { border: 2px solid navy; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("<h1 align=\"center\">My Page</h1>\r\n");
      out.write("<br>\r\n");
      out.write("<form action=\"/first/mupdate\" method=\"post\">\r\n");
      out.write("<table id=\"outer\" align=\"center\" width=\"500\" cellspacing=\"5\" \r\n");
      out.write("cellpadding=\"0\">\r\n");
      out.write("<tr><th colspan=\"2\">등록된 회원정보는 아래와 같습니다. \r\n");
      out.write("수정할 내용이 있으면 변경하고, 수정하기 버튼을 누르세요.</th></tr>\r\n");
      out.write("<tr><th width=\"120\">이름</th>\r\n");
      out.write("	<td><input type=\"text\" name=\"username\" \r\n");
      out.write("		value=\"");
      out.print( member.getUserName() );
      out.write("\" readonly></td></tr>\r\n");
      out.write("<tr><th width=\"120\">아이디</th>\r\n");
      out.write("	<td><input type=\"text\" name=\"userid\" \r\n");
      out.write("		value=\"");
      out.print( member.getUserId() );
      out.write("\" readonly></td></tr>\r\n");
      out.write("<tr><th width=\"120\">암호</th>\r\n");
      out.write("	<td><input type=\"password\" name=\"userpwd\" id=\"upwd\" \r\n");
      out.write("		value=\"");
      out.print( member.getUserPwd() );
      out.write("\"></td></tr>\r\n");
      out.write("<tr><th width=\"120\">암호확인</th>\r\n");
      out.write("	<td><input type=\"password\" id=\"upwd2\"></td></tr>\r\n");
      out.write("<tr><th width=\"120\">성별</th>\r\n");
      out.write("	<td>\r\n");
      out.write("		");
 if(member.getGender().equals("M")){ 
      out.write("\r\n");
      out.write("		<input type=\"radio\" name=\"gender\" value=\"M\" checked> 남자 &nbsp;\r\n");
      out.write("		<input type=\"radio\" name=\"gender\" value=\"F\"> 여자\r\n");
      out.write("		");
 }else{ 
      out.write("\r\n");
      out.write("		<input type=\"radio\" name=\"gender\" value=\"M\"> 남자 &nbsp;\r\n");
      out.write("		<input type=\"radio\" name=\"gender\" value=\"F\" checked> 여자\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("	</td></tr>\r\n");
      out.write("<tr><th width=\"120\">나이</th>\r\n");
      out.write("	<td><input type=\"number\" name=\"age\" min=\"19\" \r\n");
      out.write("		value=\"");
      out.print( member.getAge() );
      out.write("\"></td></tr>\r\n");
      out.write("<tr><th width=\"120\">전화번호</th>\r\n");
      out.write("	<td><input type=\"tel\" name=\"phone\" \r\n");
      out.write("		value=\"");
      out.print( member.getPhone() );
      out.write("\"></td></tr>\r\n");
      out.write("<tr><th width=\"120\">이메일</th>\r\n");
      out.write("	<td><input type=\"email\" name=\"email\" \r\n");
      out.write("		value=\"");
      out.print( member.getEmail() );
      out.write("\"></td></tr>\r\n");
      out.write("<tr><th width=\"120\">취미</th>\r\n");
      out.write("	<td>\r\n");
      out.write("		<table width=\"350\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"hobby\" value=\"game\" ");
      out.print( checked[0] );
      out.write("> 게임</td>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"hobby\" value=\"reading\" ");
      out.print( checked[1] );
      out.write("> 독서</td>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"hobby\" value=\"climb\" ");
      out.print( checked[2] );
      out.write("> 등산</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"hobby\" value=\"sport\" ");
      out.print( checked[3] );
      out.write("> 운동</td>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"hobby\" value=\"music\" ");
      out.print( checked[4] );
      out.write("> 음악듣기</td>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"hobby\" value=\"movie\" ");
      out.print( checked[5] );
      out.write("> 영화보기</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"hobby\" value=\"travel\" ");
      out.print( checked[6] );
      out.write("> 여행</td>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"hobby\" value=\"cook\" ");
      out.print( checked[7] );
      out.write("> 요리</td>\r\n");
      out.write("			<td><input type=\"checkbox\" name=\"hobby\" value=\"etc\" ");
      out.print( checked[8] );
      out.write("> 기타</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</td></tr>\r\n");
      out.write("<tr><th width=\"120\">기타 정보</th>\r\n");
      out.write("	<td><textarea name=\"etc\" rows=\"3\" cols=\"50\">");
      out.print( member.getEtc() );
      out.write("</textarea></td></tr>\r\n");
      out.write("<tr><th colspan=\"2\">\r\n");
      out.write("	<input type=\"submit\" value=\"수정하기\"> &nbsp; \r\n");
      out.write("	<a href=\"/first/mdelete?userid=");
      out.print( member.getUserId() );
      out.write("\">탈퇴하기</a> &nbsp;\r\n");
      out.write("	<a href=\"javascript:history.go(-1);\">이전페이지로 이동</a>\r\n");
      out.write("</th></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
